window.CALENDAR_DATA = {
  university: {
    id: "omgmu",
    shortName: "ОмГМУ",
    name: "Омский государственный медицинский университет",
    city: "Омск",
    timezone: "Asia/Omsk",
    brandLetter: "О",
    themeColor: "#1559d6",
  },
  apiBase: "https://kgmu-calendar-api.containerapps.ru",
  offer: {
    price: "490 ₽",
    academicYear: "2026/27",
    semester: 1,
    expires: "31 августа 2027",
    testMode: true,
    checkoutEnabled: false,
  },
  selectionModel: {
    firstStepLabel: "Программа",
    groupCodesAreDynamic: true,
    groupCodePattern: null,
    source: "https://omsk-osma.ru/studentam/raspisanie-zanyatiy",
  },
  faculties: [
    {
      id: "medicine",
      name: "Лечебный факультет",
      short: "Лечебное дело",
      icon: "Л",
      courses: 6,
      groups: {},
      streams: { 4: ["1", "2"], 5: ["1", "2"], 6: ["1", "2"] },
      scheduleParts: { 4: ["lectures", "cycles"], 5: ["lectures", "cycles"], 6: ["lectures", "cycles"] },
    },
    {
      id: "medicine-international",
      name: "Лечебное дело для иностранных граждан",
      short: "Лечебное дело — иностранные граждане",
      icon: "И",
      courses: 5,
      groups: {},
      streams: { 1: ["1", "2"], 2: ["1", "2"] },
      scheduleParts: { 4: ["lectures", "cycles"] },
      separateProgram: true,
    },
    {
      id: "preventive-medicine",
      name: "Медико-профилактический факультет",
      short: "Медико-профилактическое дело",
      icon: "М",
      courses: 6,
      groups: {},
      scheduleParts: { 4: ["front", "cycles"], 5: ["front", "cycles"], 6: ["front", "cycles"] },
    },
    {
      id: "pediatrics",
      name: "Педиатрический факультет",
      short: "Педиатрия",
      icon: "П",
      courses: 6,
      groups: {},
      scheduleParts: { 4: ["lectures", "cycles"], 5: ["lectures", "cycles"], 6: ["lectures", "cycles"] },
    },
    {
      id: "dentistry",
      name: "Стоматологический факультет",
      short: "Стоматология",
      icon: "С",
      courses: 5,
      groups: {},
      scheduleParts: { 4: ["lectures", "cycles"], 5: ["lectures", "cycles", "electives"] },
    },
    {
      id: "pharmacy",
      name: "Фармацевтический факультет",
      short: "Фармация",
      icon: "Ф",
      courses: 5,
      groups: {},
      variants: { 1: ["contact", "distance"] },
    },
  ],
};
